# Generated by Django 5.0.6 on 2024-07-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_speakers_remove_event_sponsors_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='total_tickets',
            new_name='tickets',
        ),
        migrations.AddField(
            model_name='event',
            name='registered_users',
            field=models.TextField(default='[]'),
        ),
    ]
