# Generated by Django 5.0.6 on 2024-07-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rename_total_tickets_event_tickets_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='vip_tickets',
            new_name='available_normal_tickets',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='ticket_price',
            new_name='normal_ticket_price',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='tickets',
            new_name='total_tickets',
        ),
        migrations.AddField(
            model_name='event',
            name='available_vip_tickets',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
